spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_userDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10   # max active connections
      minimum-idle: 5         # keep some idle connections ready
      idle-timeout: 30000     # 30s before closing idle connections
      max-lifetime: 1800000   # 30m connection lifetime
      connection-timeout: 20000 # 20s to wait for a connection before failing

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

